export const MESSAGE_SEND = "MESSAGE/MESSAGE_SEND";
export const MESSAGE_DELETE = "MESSAGE/MESSAGE_DELETE";
export const MESSAGE_EDIT = "MESSAGE/MESSAGE_EDIT";
export const MESSAGE_LOADING = "MESSAGE/MESSAGE_LOADING";
export const MESSAGE_COMPLETED = "MESSAGE/MESSAGE_COMPLETED";
