export const MESSAGE_SEND = "MESSAGE/MESSAGE_SEND";
export const MESSAGE_DELETE = "MESSAGE/MESSAGE_DELETE";
export const MESSAGE_EDIT = "MESSAGE/MESSAGE_EDIT";
export const MESSAGE_LIST_LOADING = "MESSAGE/MESSAGE_LIST_LOADING";
export const MESSAGE_LIST_COMPLETED = "MESSAGE/MESSAGE_LIST_COMPLETED";
